### ISSUE TITLE
Discord disconnects and unknown opcode: 9

### ISSUE THREAD

**Issue by Hendrik83** [tsebring/ArkBot#10]
Hi, 

The bot is not auto updating but instead it keeps disconnecting and saying unknown opcode: 9

![h254-dyj9w-778_587](https://cloud.githubusercontent.com/assets/60172/25490747/07e9909c-2b6e-11e7-8db0-2a92dd35cf2b.png)

`-- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bij ArkBot.ArkDiscordBot.<_timer_Callback>d__19.MoveNext() in R:\ARK\ArkBot\ArkBot\ArkDiscordBot.cs:regel 324
2017-04-23 01:01:13,990 [41] ERROR ArkBot.ArkDiscordBot - Error when attempting to change bot info channel topic
Discord.Net.HttpException: The server responded with error 401 (Unauthorized)
   bij Discord.Net.Rest.RestSharpEngine.<Send>d__10.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Discord.Net.Rest.RestClient.<Send>d__29.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Discord.Net.Rest.RestClient.<Send>d__25`1.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Discord.Channel.<Edit>d__50.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bij ArkBot.ArkDiscordBot.<_timer_Callback>d__19.MoveNext() in R:\ARK\ArkBot\ArkBot\ArkDiscordBot.cs:regel 324`

`Error when attempting to change bot info channel topic
[_timer_Callback(R:\ARK\ArkBot\ArkBot\ArkDiscordBot.cs:329)]

<Exception>
  <Discord.Net.HttpException>
    <Current>
      <StatusCode>Unauthorized</StatusCode>
    </Current>
    <Message>The server responded with error 401 (Unauthorized)</Message>
    <TargetSite>Void MoveNext()</TargetSite>
    <Source>Discord.Net</Source>
    <StackTrace><![CDATA[bij Discord.Net.Rest.RestSharpEngine.<Send>d__10.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bij Discord.Net.Rest.RestClient.<Send>d__29.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bij Discord.Net.Rest.RestClient.<Send>d__25`1.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bij Discord.Channel.<Edit>d__50.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
bij ArkBot.ArkDiscordBot.<_timer_Callback>d__19.MoveNext() in R:\ARK\ArkBot\ArkBot\ArkDiscordBot.cs:regel 324]]></StackTrace>
  </Discord.Net.HttpException>
</Exception>`

**Comment by SirCaveman** [comment]
How do you start the bot?? I filled in all the fields as best i could in the defaultconfig.json file but where to put it? or just rename it to config.json ans leave it in the arkbot folder where it is located? 
I am trying to start it through git desktop but i cant get it to clone there... im quite new at this stuff so im struggeling a bit :S

**Comment by SirCaveman** [comment]
Ok i ran it with visual studio in the end... took me a while :S but now it says i have to place config.json in the application directory?? i have both files filled in, defaultconfig.json and config.json and placed in arkbot directory... any advise would be very welcome!

**Comment by tsebring** [comment]
This is a problem with the dependency Discord.Net that will be fixed in their future major update (v.1.0). There is no workaround except just wait for it to reconnect again.
