### ISSUE TITLE
multi-server branch - Ragnarok failed to update.

### ISSUE THREAD

**Issue by Hendrik83** [tsebring/ArkBot#16]
I see you have done some work on the bot again so i thought to try it again.

I get this with Ragnarok.
https://hastebin.com/izibotihej.tex

**Comment by tsebring** [comment]
I have not seen this error before. It could be a corrupt .arktribe-file on your server. Would it be possible to get a copy of all the .arktribe-files so that I can examine them?

**Comment by Hendrik83** [comment]
Here is my savedarks folder. 

https://drive.google.com/file/d/0B8VvDxvLcGrFd0JuQ2ZPQ3dqVUE/view?usp=drivesdk

**Comment by tsebring** [comment]
These files are corrupt (every byte is 0x00).
1215092808.arktribe
1645610428.arktribe

**Comment by Hendrik83** [comment]
Ah it worked thx.
How did you find the corrupted ones?

**Comment by tsebring** [comment]
I can run everything through the debugger and get more info.

In the latest check-in, the exception message has been updated to include the filename of the profile that failed to extract so it is easier to locate and fix.
