### ISSUE TITLE
ArkBot crashing

### ISSUE THREAD

**Issue by urdeadagain** [tsebring/ArkBot#19]
Hi Mate, 
had this working briefly, from what i saw its flipping amazing.
I am really struggling getting this fully configured, bot isnt connecting to my discord, would love it if you could spare 5 mins or so :D

**Comment by tsebring** [comment]
There should be crash logs saved in the /logs directory.  What do they say?

**Comment by urdeadagain** [comment]
[applicationcrash_CurrentDomain_UnhandledException_2017-09-28.21.12.26.7381.log](https://github.com/tsebring/ArkBot/files/1343187/applicationcrash_CurrentDomain_UnhandledException_2017-09-28.21.12.26.7381.log)

thanks for this, attached is the file.

Loving the tool, and its currently running again.

I have most of it working, but i suspect some of the issues may be me :(

The steam logging in works for a while then kicks me out and just puts me on a logging in loop.

I would love to get this fully working, but wanted to also ask, is there any way of locking down the steam profile to whats available to see.
I operate very busy eu servers on pvpve and I know people will abuse the fact they can see other players locations and dinos.

PS if you want a busy ark server platform to test, (apologies if you have this already), we would love to be that platform.

**Comment by tsebring** [comment]
The attached crash log indicates it crashed while the application was closing. Is that what happened or are there multiple crash logs?

Role-based access control for specific features is indeed something that is required for any and all pvp-scenarios. It is not currently available, but I understand the need for it. I will see what I can do going forward.

When the steam login puts you in a loop is the authentication cookie still being sent with the request to the server? Use dev tools (F12, then refresh page) in Chrome to check the cookie.
![image](https://user-images.githubusercontent.com/408350/31017075-989dc29c-a527-11e7-97ea-afd8b8acd231.png)

The project mostly needs more developers to be involved. Testing is less of an issue. The codebase is already pretty big and there is no shortage of features to add, modules that need improvement and ARK changes to keep up with.

**Comment by urdeadagain** [comment]
Hi

I am currently at work, but will supply you with further info's when I get home this evening.
There were multiple crash logs, which I will supply more of.

I am a BI developer, so any help i can provide would be happy to throw your way, although not being a c# dev, I cant imagine my skills are going to be of any use.

Its a shame there aren't a mass of developers on this thread helping out, as imo this is one of the best projects out there, pulling together a lot of the tools into one package.
Its certainly something, I would really like to adopt for my ark servers, although as you said testing is in no shortfall at the moment.

Keep up with the project, its brilliant from what I have seen so far and I will post more details when I arrive home later this evening.

**Comment by urdeadagain** [comment]
![capture](https://user-images.githubusercontent.com/26038442/31027297-9f561e80-a541-11e7-819d-37dbb645ae3b.PNG)
capture from the cookie

**Comment by tsebring** [comment]
Is the web app open so that I can examine the loop? It is a weird problem that I have not come across before and most of the components involved are standard .NET ones. You can reach me on Discord, my discord tag is Tobias#5051.

**Comment by urdeadagain** [comment]
Hi it is, logging in to discord now :D
