### ISSUE TITLE
two start problems - may find help here

### ISSUE THREAD

**Issue by DomSylon** [tsebring/ArkBot#33]
Hey,

first of all the BOT is great. To work perfectly for me I have two little problems.

1) In Discord Channel I can't use the "!admin" command. Only in private chat. Even if I type "!commands" it will not show up. Is there a way to enable "!admin" in server chat?

2) Setting up WebApp is complete but when I try to login with my Steam-Account it says access denied :( SteamID is the config file under admin accounts.

Can some if you guys please help me?

Also happy christmas!

Greetings

**Comment by tsebring** [comment]
Install the new release https://github.com/tsebring/ArkBot/releases/tag/1.82 and use these settings to allow admin/developer commands to be sent in public channels.
```json
{
  "discord": {
    "accessControl": {
      "channels": {
        "public": [ "@everyone", "admin", "developer" ],
        "private": [ "@everyone", "admin", "developer" ]
      },
      "commands": {
        "admin": [ "admin", "developer" ],
        "cloud": [ "admin", "developer" ],
        "rcon": [ "admin", "developer" ],
        "debug": [ "developer" ],
        "commands": [ "@everyone" ],
        "version": [ "@everyone" ],
        "servers": [ "@everyone" ],
        "linksteam": [ "@everyone" ],
        "unlinksteam": [ "@everyone" ],
        "whoami": [ "@everyone" ],
        "disabled": [ "@everyone" ]
      }
    }
  }
}
```

---

It is not possible for me to know why you get "access denied" from the information you have provided. Most common problem is errors in the configuration or the web app being unable to connect to the web API.

You can access the main web API data endpoint on http://127.0.0.1:60001/api/servers if you use the default configuration. It will be cached so use `Ctrl + F5` when reloading.

If you want help you can contact me on Discord, my tag is Tobias#5051.

**Comment by DomSylon** [comment]
Update with Discord config works perfect !

For running the WebApp I just forgot the Steam API ID ... now fixed and works perfect as well.

Thanks a lot

**Comment by tsebring** [comment]
No problem! :)
