### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by blast1987** [tsebring/ArkBot#36]
Hello,
is it possible to run this app on a linux server?
I have ARK installed on my ubuntu server and i'd like to install arkbot

thanks

**Comment by Foppa01** [comment]
As for now i think the answere is no. it is build on .NET

Regards
Foppa

**Comment by blast1987** [comment]
But is it possibile to use it to only connects to an existing ark server istance?

I want to try to install to my PC and make it connects to my ubuntu box
is that possible?

**Comment by Foppa01** [comment]
Only with some reduced functionality. The ArkBot need to have full access to the running ARK-Server instance for proper functionality. With other words, it can work with some features but arkbot needs to be running on the same hosts as the Ark server instance. More information [here](https://github.com/tsebring/ArkBot/wiki/Frequently-Asked-Questions#are-non-local-servers-supported)

**Comment by tsebring** [comment]
Everything @Foppa01 said is correct. It is built on .NET WPF which mono does not support. Running it on your PC will work fine except the server management commands in Discord will not work. You can disable those commands in the access control settings.
