### ISSUE TITLE
Admin not working

### ISSUE THREAD

**Issue by doublee313** [tsebring/ArkBot#37]
I have entered my info as shown below for my admins:

"userRoles": {
    "admin": [ "76561198222385276", "76561198007969068", "76561198031769506", "76561198098335823", "76561198215383151", "76561198154537440" ]
  },

I can't seem to get the admin server sections working. It still logs me in as a player. Can you offer any help?

Awesome utility! Keep up the great work!

**Comment by tsebring** [comment]
Did you restart the application or use the menu option to `Reload partial config`?
