### ISSUE TITLE
Player Levels showing wrong levels

### ISSUE THREAD

**Issue by doublee313** [tsebring/ArkBot#39]
The player levels are displaying wrong. I have a user showing level 8 and he's level 180 or something. Just reporting issue.

**Comment by tsebring** [comment]
Not sure what kind of configuration you have for that to happen. Player levels work fine in a standard server setup without any mods that might interfere and this issue has not come up before.

Are you able to find out what in your particular setup is causing it?

**Comment by doublee313** [comment]
Tse,

This issue went away when I refreshed the config file from the app. It seems this has to be done to get things working 100%. At least on my end :)

On a separate note, you might want to add this to your Discord instructions to make it easier for the server admins to get their bot to pop up in the channel. I had to dig around for this and might save others sometime :)

Paste the URL listed below into your browser and replace "CLIENT_ID" with your client ID number. Hit enter and select the desired Discord server. Once this is done, the bot will show up in your server!
https://discordapp.com/oauth2/authorize?client_id=CLIENT_ID&scope=bot

Thanks. I hope to see more updates and don't mind donating, etc. This is a great utility. If we could get the permissions with more options in the config this would be awesome (allow us to disable restarts, etc). Also, move LISTPLAYERS and other commands that would provide the normal players more info. I'm not a programmer, however I can help with some feature requests and make some mock screenshots. 

Again, amazing job and I know your busy :)

**Comment by tsebring** [comment]
It's good that the issue went away!

I will add it to the wiki, thanks! Next release of the bot will have an updated configuration interface inside the application with a lot more instructions and validation. Not sure when it will be finished but it has been in the works for some time.
