### ISSUE TITLE
Documentation/ability to edit home page.

### ISSUE THREAD

**Issue by Magesw** [tsebring/ArkBot#42]
I would like the ability or at least some documentation on how to edit the home page so I can add some of my own links or move things around a bit.

For example I want to add a link back to my servers main website and move the External Resources area to the left side bar.

Thanks!

**Comment by tsebring** [comment]
It would make sense to be able to configure the links from Ark Bot but at this time you cannot. The option you have to do this is to make the changes to the web app and recompile it yourself.

To edit the web app you have to install angular-cli and the prerequisites Node and NPM
https://github.com/angular/angular-cli#installation
https://github.com/angular/angular-cli#prerequisites

* Clone the repo (or download the code), the web application code is found in `ArkBot\WebApp`.
* Make the changes you want in `ArkBot\WebApp\src\app\server-list\server-list.component.html`.
* Run the terminal command `ng build --prod --bh /` in `ArkBot\WebApp`.
* Replace the files in your Ark Bot installation `WebApp` directory with the files from `ArkBot\WebApp\dist`.
