### ISSUE TITLE
linksteam

### ISSUE THREAD

**Issue by r2range** [tsebring/ArkBot#53]
!linksteam ID
!linksteam full profile link

both doesnt work i get My logic circuits cannot process this command! I am just a bot after all... :(

back,

**Comment by megoesrawr** [comment]
Please fix this.

**Comment by tsebring** [comment]
This issue is now resolved thanks to https://github.com/tsebring/ArkBot/pull/56 from @megoesrawr!

Code is available on the beta-branch
https://github.com/tsebring/ArkBot/tree/beta

CI-build is available from MyGet
https://www.myget.org/F/arkbot-beta/api/v2/package/ArkBot
