### ISSUE TITLE
JSON Error on Windows Server

### ISSUE THREAD

**Issue by Izion** [tsebring/ArkBot#62]
Hi,
I have been trying to get your bot running on our cluster, when starting the application on my home Windows 10 pc it will load and read the config file. The same file copied to the Windows Server 2016 and I can't get rid of the following error

![boterror](https://user-images.githubusercontent.com/6631073/41544932-e394c24c-7311-11e8-97b1-55de889634a0.png)

I read through a few topics and tried installing VS2017 but still no luck, got a feeling its something simple anyone else had this?

Thanks

**Comment by Izion** [comment]
Downloaded the latest beta source, built local and the error has gone.

**Comment by Lewimaron** [comment]
We've been having the same issue on our cluster. We've tried building from the latest beta source but we're still getting the same error.
