### ISSUE TITLE
Access denied and unable to login

### ISSUE THREAD

**Issue by Lewimaron** [tsebring/ArkBot#64]
I've tried getting ARKBot set up on my server cluster however it's not working. When I connect to the domain all I get is a message saying access denied. When I try and login steam just returns back to the same page.
https://cdn.discordapp.com/attachments/453222297659244554/460893005876953089/unknown.png

**Comment by JamieKG** [comment]
Are you using the latest version ?
download from 
https://www.myget.org/F/arkbot-beta/api/v2/package/ArkBot
open as zip-archive or change extension to .zip then the files you need to run are under the directory of tools

**Comment by Lewimaron** [comment]
Not entirely sure how but it's working now. I used a config from someone else and changed the settings I needed and it's fine.
