### ISSUE TITLE
NullReferenceException with !stats command

### ISSUE THREAD

**Issue by Hendrik83** [tsebring/ArkBot#9]
Hi, 

Nice program first of all!

But i get the following error with the stats command and only on the island map.
Its working for the center en scorched map.

`2017-04-15 19:36:55,205 [36] ERROR ArkBot.ArkDiscordBot - "!stats" command error...
System.NullReferenceException: De objectverwijzing is niet op een exemplaar van een object ingesteld.
   bij ArkBot.Commands.StatsCommand.<Run>d__18.MoveNext() in R:\ARK\ArkBot\ArkBot\Commands\StatsCommand.cs:regel 136
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   bij Discord.Commands.CommandService.<>c__DisplayClass28_0.<<Discord-IService-Install>b__1>d.MoveNext()`

`"!stats" command error...
[Commands_CommandErrored(R:\ARK\ArkBot\ArkBot\ArkDiscordBot.cs:553)]

<Exception>
  <System.NullReferenceException>
    <Current />
    <Message>De objectverwijzing is niet op een exemplaar van een object ingesteld.</Message>
    <TargetSite>Void MoveNext()</TargetSite>
    <Source>ArkBot</Source>
    <StackTrace><![CDATA[bij ArkBot.Commands.StatsCommand.<Run>d__18.MoveNext() in R:\ARK\ArkBot\ArkBot\Commands\StatsCommand.cs:regel 136
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
bij System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
bij Discord.Commands.CommandService.<>c__DisplayClass28_0.<<Discord-IService-Install>b__1>d.MoveNext()]]></StackTrace>
  </System.NullReferenceException>
</Exception>`

**Comment by tsebring** [comment]
Hey,
Did not see this before now. This problem may have been due to a case where only a single distinct species exist when running the stats-commands. Should be fixed now in de09b14239c65c2a7e6564779e299c81b9200f66.

**Comment by Hendrik83** [comment]
Thanks.  I have some problems that it does not update.  Will make a new report soon.
